


devDash:
  keiranworrell:
    DevDashboard:
      actions:
        buildAndPushFront.yaml: CI Frontend
        buildAndPushBack.yaml: CI Backend
    MovieGuess:
      actions:
        build.yml: CI build
    CrawlersDescent:
      actions:
        - null
